[pytest]

# testpaths → Testlerin bulunduğu dizin
testpaths = tests/ui
python_files = test_*.py
python_functions = test_*
python_classes = Test*

# addopts → Pytest çalıştırıldığında varsayılan ek parametreler
addopts = --browser chromium --tracing=retain-on-failure --html=C:/Users/PC/Desktop/test_framework_full/reports/html-reports/report.html --self-contained-html

markers =
    smoke: Hızlı çalışan kritik testler
    regression: Tüm sistem testi
    api: API testleri

